baseURL = "https://londoncitypool.com/"
title = "London City Pool League"
subtitle = "London's premier 8-ball pool league"
languageCode = "en-gb"
theme = "hugo-travelify-theme"
canonifyURLs = true

[params]
    # Tell me who you are
    author = "Josh Cooke"
    site_description = "London's premier 8-ball pool league"
    logo = "lcp-logo-200.png"
    title_in_logo = true # set to true if you want the title along with the logo
    disable_mathjax = true # set to true to disable MathJax

    # Format dates with Go's time formatting
    date_format = "02 January 2006"

    # Add custom assets with their paths relative to the static folder
    custom_css = []
    custom_js  = []

[server]
[[server.headers]]
    for = '/**'
[server.headers.values]
    Content-Security-Policy = "default-src 'self' https://app.londoncitypool.com http://localhost:7070; child-src 'self'; font-src 'self' data:; form-action 'self'; frame-src 'self' https://docs.google.com; frame-ancestors 'self' https://docs.google.com; img-src 'self'; object-src 'none'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdn.jsdelivr.net https://unpkg.com https://cdnjs.cloudflare.com/ https://app.londoncitypool.com;"

[[menu.main]]
    name  = "Home"
    url   = "/"
    weight = 10
    
[[menu.main]]
    name  = "League"
    url   = "/league/"
    weight = 20

[[menu.main]]
    name  = "Fixtures"
    url   = "/fixtures/"
    weight = 30

[[menu.main]]
    name  = "Player Stats"
    url   = "/stats/"
    weight = 40

#[[menu.main]]
#    name  = "Division 1"
#    url   = "/stats/div1/"
#    parent = "Player Stats"
#    weight = 10
#
#[[menu.main]]
#    name  = "Division 2"
#    url   = "/stats/div2/"
#    parent = "Player Stats"
#    weight = 20

[[menu.main]]
    name  = "KO Competitions"
    url   = "/ko/singles/"
    weight = 50

[[menu.main]]
    name  = "Singles"
    url   = "/ko/singles/"
    parent = "KO Competitions"
    weight = 10

[[menu.main]]
    name  = "Doubles"
    url   = "/ko/doubles/"
    parent = "KO Competitions"
    weight = 20

[[menu.main]]
    name  = "Team"
    url   = "/ko/team/"
    parent = "KO Competitions"
    weight = 30

#[[menu.main]]
#    name  = "Teams"
#    url   = "/teams/"
#    weight = 60

#[[menu.main]]
#    name  = "Registered Players"
#    url   = "/registered-players/"
#    parent = "Teams"
#    weight = 10

[[menu.main]]
    name  = "Hall of Fame"
    url   = "/hall-of-fame/"
    weight = 70

[[menu.main]]
    name  = "News"
    url   = "/news/"
    weight = 75

[[menu.main]]
    name  = "Resources"
    url   = "/admin/constitution"
    weight = 80

[[menu.main]]
    name  = "Constitution"
    url   = "/admin/constitution"
    parent = "Resources"
    weight = 10

[[menu.main]]
    name  = "Winter League"
    parent = "Resources"
    weight = 20

[[menu.main]]
    name  = "Winter League Rules"
    url   = "/admin/winter-rules"
    parent = "Winter League"
    weight = 10

#[[menu.main]]
#    name  = "Winter League Scoresheet"
#    url   = "/citypoolleague_resultsheet.pdf"
#    parent = "Winter League"
#    weight = 20

[[menu.main]]
    name  = "Summer League"
    parent = "Resources"
    weight = 30

[[menu.main]]
    name  = "Summer League Rules"
    url   = "/admin/summer-rules"
    parent = "Summer League"
    weight = 10

#[[menu.main]]
#    name  = "Summer League Scoresheet"
#    url   = "/citypoolleague_resultsheet.pdf"
#    parent = "Summer League"
#    weight = 20

#[[menu.main]]
#    name  = "Player Registration"
#    url   = "/admin/forms/registration"
#    parent = "Resources"
#    weight = 40

#[[menu.main]]
#    name  = "Result Submission"
#    url   = "/admin/forms/submission"
#    parent = "Resources"
#    weight = 50

[[menu.main]]
    name  = "Admin Portal"
    url   = "https://app.londoncitypool.com/"
    parent = "Resources"
    weight = 60
